project_name: tuatara

processes:
  trimmomatic_low_qual_window:
    process_type: trimmomatic
    command_line_template: "trimmomatic-pe -phred33 [% args %] SLIDINGWINDOW:3:30 MINLEN:70"
    exec_type: paired
  fastqc:
    process_type: fast_qc
    command_line_template: "fastqc [% args %] --outdir [% out_dir %]"
    exec_type: all_files
  quake_k12:
    process_type: quake
    command_line_template: "quake.py [% args %] -k 12 -p 10"
    exec_type: all_pairs
  abyss_k60:
    process_type: abyss
    command_line_template: "abyss-pe [% args %] k=60 name=[% config.project_name %]"
    exec_type: all_pairs
