project_name: tuatara

processes:
  trimmomatic_low_qual_window:
    process_type: trimmomatic
    command_line_template: "trimmomatic-pe -threads 32 -phred33 [% args %] SLIDINGWINDOW:3:30 MINLEN:50"
    exec_type: paired_end
  trimmomatic_crop_mate_pairs:
    process_type: trimmomatic
    command_line_template: "trimmomatic-pe -phred33 [% args %] CROP:40"
    exec_type: mate_pair
  fastqc:
    process_type: fast_qc
    command_line_template: "fastqc [% args %] --outdir [% out_dir %]"
    exec_type: all_files
  quake_k12:
    process_type: quake
    command_line_template: "quake.py [% args %] -k 20 -p 32"
    exec_type: all_pairs
  abyss_k60:
    process_type: abyss
    command_line_template: "abyss-pe [% args %] np=32 k=63 name=[% config.project_name %]"
    exec_type: all_pairs

